/**
 * @module monitoring/telemetry
 * OpenTelemetry configuration for Claude Code, matching the official
 * claude-code-monitoring-guide patterns.
 *
 * Key insight from GitHub issue #15417:
 *   Rich telemetry (tokens, costs, tool usage) exports via the
 *   LOGS/EVENTS protocol, not metrics. You need OTEL_LOGS_EXPORTER.
 *
 * Key gotcha from issue #34178:
 *   DISABLE_TELEMETRY (Anthropic's internal Statsig) is DIFFERENT from
 *   CLAUDE_CODE_ENABLE_TELEMETRY (user-managed OTel). Disabling the
 *   former can break Opus 1M and Channels.
 */

import type { USD } from '../types/core.js';
import { USD as makeUSD } from '../types/core.js';

// ── Model Pricing Table ─────────────────────────────────────────

export type ModelPricing = {
  readonly model: string;
  readonly inputPerMillion: number;
  readonly outputPerMillion: number;
  readonly cacheWritePerMillion: number;
  readonly cacheReadPerMillion: number;
};

export const MODEL_PRICING: ReadonlyArray<ModelPricing> = [
  {
    model: 'claude-opus-4-6',
    inputPerMillion: 15,
    outputPerMillion: 75,
    cacheWritePerMillion: 18.75,
    cacheReadPerMillion: 1.5,
  },
  {
    model: 'claude-sonnet-4-6',
    inputPerMillion: 3,
    outputPerMillion: 15,
    cacheWritePerMillion: 3.75,
    cacheReadPerMillion: 0.3,
  },
  {
    model: 'claude-haiku-4-5',
    inputPerMillion: 0.8,
    outputPerMillion: 4,
    cacheWritePerMillion: 1.0,
    cacheReadPerMillion: 0.08,
  },
] as const;

export function calculateCost(
  model: string,
  inputTokens: number,
  outputTokens: number,
  cacheWriteTokens: number = 0,
  cacheReadTokens: number = 0,
): USD {
  // Match by exact model name first, then by model family keyword (opus/sonnet/haiku).
  // Uses explicit keyword matching to avoid false positives from substring collision.
  const pricing =
    MODEL_PRICING.find((p) => model === p.model) ??
    MODEL_PRICING.find((p) => {
      if (p.model.includes('opus')) return model.includes('opus');
      if (p.model.includes('haiku')) return model.includes('haiku');
      if (p.model.includes('sonnet')) return model.includes('sonnet');
      return false;
    }) ??
    MODEL_PRICING[1]!;
  const cost =
    (inputTokens * pricing.inputPerMillion) / 1_000_000 +
    (outputTokens * pricing.outputPerMillion) / 1_000_000 +
    (cacheWriteTokens * pricing.cacheWritePerMillion) / 1_000_000 +
    (cacheReadTokens * pricing.cacheReadPerMillion) / 1_000_000;
  return makeUSD(cost);
}

// ── Environment Variable Generator ──────────────────────────────

export type OtelBackend = 'prometheus' | 'datadog' | 'honeycomb' | 'signoz' | 'grafana' | 'custom';

/** Valid backend values — used for runtime validation of CLI input */
export const VALID_BACKENDS: ReadonlySet<string> = new Set<OtelBackend>([
  'prometheus',
  'datadog',
  'honeycomb',
  'signoz',
  'grafana',
  'custom',
]);

/** Validate and sanitize a backend string from CLI input */
export function validateBackend(input: string): OtelBackend {
  return VALID_BACKENDS.has(input) ? (input as OtelBackend) : 'prometheus';
}

/** Sanitize a string for safe interpolation into YAML/shell output */
function sanitizeForInterpolation(value: string): string {
  return value.replace(/[\r\n]/g, '');
}

export type OtelConfig = {
  readonly backend: OtelBackend;
  readonly endpoint: string;
  readonly protocol: 'grpc' | 'http/protobuf' | 'http/json';
  readonly authHeader?: string;
  readonly exportIntervalMs: number;
  readonly logPrompts: boolean;
  readonly logToolDetails: boolean;
  readonly includeSessionId: boolean;
};

export function generateOtelEnvVars(config: OtelConfig): Record<string, string> {
  const env: Record<string, string> = {
    // Master switch — user-managed OTel (NOT the internal Statsig toggle)
    CLAUDE_CODE_ENABLE_TELEMETRY: '1',

    // Both exporters needed — events flow through LOGS, not just METRICS
    OTEL_METRICS_EXPORTER: 'otlp',
    OTEL_LOGS_EXPORTER: 'otlp',

    // Protocol and endpoint
    OTEL_EXPORTER_OTLP_PROTOCOL: config.protocol,
    OTEL_EXPORTER_OTLP_ENDPOINT: config.endpoint,

    // Export interval
    OTEL_METRIC_EXPORT_INTERVAL: String(config.exportIntervalMs),
  };

  if (config.authHeader) {
    env['OTEL_EXPORTER_OTLP_HEADERS'] = config.authHeader;
  }

  // Privacy controls
  if (config.logPrompts) {
    env['OTEL_LOG_USER_PROMPTS'] = '1';
  }
  if (config.logToolDetails) {
    env['OTEL_LOG_TOOL_DETAILS'] = '1';
  }

  // Cardinality controls
  if (config.includeSessionId) {
    env['OTEL_METRICS_INCLUDE_SESSION_ID'] = '1';
  }

  return env;
}

export function generateOtelShellScript(config: OtelConfig): string {
  const vars = generateOtelEnvVars(config);
  const lines = Object.entries(vars).map(([k, v]) => `export ${k}="${v}"`);
  return `#!/bin/bash
# Claude Code OTel Configuration
# Generated by @jadecli/claude-knowledge-sdk
# Backend: ${config.backend}
#
# IMPORTANT: Rich telemetry data (tokens, costs, tool usage) exports
# via the LOGS protocol. You MUST have OTEL_LOGS_EXPORTER=otlp set.
# See: github.com/anthropics/claude-code/issues/15417
#
# WARNING: Do NOT confuse this with DISABLE_TELEMETRY, which controls
# Anthropic's internal Statsig metrics and can break paid features.
# See: github.com/anthropics/claude-code/issues/34178

${lines.join('\n')}
`;
}

// ── Docker Compose Generator ────────────────────────────────────

export function generateDockerCompose(backend: OtelBackend): string {
  switch (backend) {
    case 'prometheus':
      return `# Claude Code Monitoring Stack (Prometheus)
# From: github.com/anthropics/claude-code-monitoring-guide
version: "3.8"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"   # gRPC receiver
      - "4318:4318"   # HTTP receiver
      - "8889:8889"   # Prometheus metrics endpoint
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    deploy:
      resources:
        limits:
          memory: 1G

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
`;

    case 'signoz':
      return `# Claude Code Monitoring Stack (SigNoz)
version: "3.8"
services:
  signoz:
    image: signoz/signoz:latest
    ports:
      - "3301:3301"   # SigNoz UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
`;

    default:
      return `# Configure your ${backend} backend to receive OTLP on port 4317 (gRPC)
# Then set OTEL_EXPORTER_OTLP_ENDPOINT to point at it.
`;
  }
}

// ── OTel Collector Config Generator ──────────────────────────────
// This is the config the collector needs to receive from Claude Code
// and export to your backend.

export function generateOtelCollectorConfig(config: OtelConfig): string {
  // Parse authHeader from OTLP env format "Key=Value" to YAML "Key: Value"
  const formatAuthHeaders = (header: string): string => {
    return header
      .split(',')
      .map((pair) => {
        const eqIdx = pair.indexOf('=');
        if (eqIdx === -1) return `      ${pair.trim()}: ""`;
        return `      ${pair.slice(0, eqIdx).trim()}: "${pair.slice(eqIdx + 1).trim()}"`;
      })
      .join('\n');
  };

  const prometheusExporter =
    config.backend === 'prometheus'
      ? `  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: claude_code
  debug: {}`
      : '';

  const safeEndpoint = sanitizeForInterpolation(config.endpoint);

  const otlpExporter =
    config.backend !== 'prometheus'
      ? `  otlp:
    endpoint: "${safeEndpoint}"
    ${config.authHeader ? `headers:\n${formatAuthHeaders(sanitizeForInterpolation(config.authHeader))}` : ''}`
      : '';

  return `# OTel Collector Config for Claude Code
# Generated by @jadecli/claude-knowledge-sdk
# Backend: ${config.backend}
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 5s
    limit_mib: 512
    spike_limit_mib: 128

exporters:
${prometheusExporter}${otlpExporter}

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [${config.backend === 'prometheus' ? 'prometheusremotewrite, prometheus' : 'otlp'}]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [${config.backend === 'prometheus' ? 'debug' : 'otlp'}]
`;
}

// ── Prometheus Scrape Config ──────────────────────────────────

export function generatePrometheusConfig(): string {
  return `# Prometheus config for Claude Code monitoring
# Scrapes the OTel collector's Prometheus exporter endpoint
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
    metrics_path: /metrics

  - job_name: "claude-code"
    static_configs:
      - targets: ["otel-collector:8889"]
    metrics_path: /metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "claude_code_.*"
        action: keep
`;
}

// ── Full Setup Script ──────────────────────────────────────────

/**
 * Generate a complete setup script that:
 * 1. Creates the OTel collector config
 * 2. Creates the Prometheus config (if Prometheus backend)
 * 3. Creates the Docker Compose file
 * 4. Creates the env vars script
 * 5. Starts the stack and sources the env
 */
export function generateFullSetupScript(config: OtelConfig): string {
  return `#!/bin/bash
set -euo pipefail

# Claude Code Monitoring — Full Setup
# Generated by @jadecli/claude-knowledge-sdk
# Backend: ${config.backend}

echo "Setting up Claude Code monitoring with ${config.backend}..."

# Step 1: Create OTel collector config
mkdir -p monitoring
cat > monitoring/otel-collector-config.yaml << 'OTEL_EOF'
${generateOtelCollectorConfig(config)}OTEL_EOF

${
  config.backend === 'prometheus'
    ? `# Step 2: Create Prometheus config
cat > monitoring/prometheus.yml << 'PROM_EOF'
${generatePrometheusConfig()}PROM_EOF
`
    : '# Step 2: Skipped (not using Prometheus)'
}

# Step 3: Create Docker Compose
cat > monitoring/docker-compose.yml << 'COMPOSE_EOF'
${generateDockerCompose(config.backend)}COMPOSE_EOF

# Step 4: Create env vars script
cat > monitoring/claude-otel-env.sh << 'ENV_EOF'
${generateOtelShellScript(config)}ENV_EOF

echo ""
echo "Setup complete! To start monitoring:"
echo ""
echo "  cd monitoring && docker compose up -d"
echo "  source claude-otel-env.sh"
echo "  claude  # OTel telemetry is now enabled"
echo ""
${
  config.backend === 'prometheus'
    ? `echo "Dashboards:"
echo "  Prometheus: http://localhost:9090"
echo "  Grafana:    http://localhost:3000 (admin/admin)"
echo ""`
    : ''
}
echo "Key metrics to query:"
echo "  ${OTEL_METRICS.cost}         — total cost in USD"
echo "  ${OTEL_METRICS.tokens}  — token usage by type"
echo "  ${OTEL_METRICS.sessions}    — session count"
`;
}

// ── Key OTel Metrics Reference ──────────────────────────────────

export const OTEL_METRICS = {
  cost: 'claude_code_cost_usage_USD_total',
  tokens: 'claude_code_token_usage_tokens_total',
  apiDuration: 'claude_code_api_request_duration_ms',
  toolDuration: 'claude_code_tool_execution_duration_ms',
  sessions: 'claude_code_session_count_total',
  linesChanged: 'claude_code_lines_of_code_changed_total',
  prCount: 'claude_code_pull_request_count',
  activeTime: 'claude_code_active_time_total_ms',
} as const;

export const OTEL_LABELS = {
  userEmail: 'user_email',
  model: 'model',
  sessionId: 'session_id',
  tokenType: 'type', // input, output, cache_read, cache_write
  toolName: 'tool_name',
} as const;
